---
title: "Geography 176A"
author: "[Stone Shi](https://mycraysh.github.io/StoneGIS/)"
subtitle: 'Lab 03: Distances and the Border Zone'
output:
  html_document:
    theme: journal
---
```{r library,include=FALSE}
# SPDS
library(tidyverse)
library(sf)
library(units)

# Data
library(USAboundaries)
library(rnaturalearth)

# Visualization
library(gghighlight)
library(ggrepel)
library(knitr)

```

#Question 1

#1.1 Define a Projection
```{r,message=FALSE, warning=FALSE}
#This projection will use the North America Equidistant Conic.

eqdc = '+proj=eqdc +lat_0=40 +lon_0=-96 +lat_1=20 +lat_2=60 +x_0=0 +y_0=0 +datum=NAD83 +units=m +no_defs'
```

#1.2 Get USA state boundaries
```{r,message=FALSE, warning=FALSE}
mapdata = USAboundaries::us_states(resolution = "low") %>%
  filter(!state_name %in% c("Puerto Rico", "Alaska", "Hawaii")) %>% 
  st_transform(eqdc)
```

#1.3 - Get country boundaries for Mexico, the United States of America, and Canada
```{r,message=FALSE, warning=FALSE}
country = rnaturalearth::countries110
country_sf = st_as_sf(country) %>%
  filter(admin %in% c("Mexico","United States of America", "Canada")) %>%
  st_transform(eqdc)
```

#1.4 - Get city locations from the CSV file
```{r,message=FALSE, warning=FALSE}
uscities = readr::read_csv("D:/LifeInUCSB/Study/GEOG176A/week2/assignment5/geog-176A-labs/data/uscities.csv")
sf_uscities = st_as_sf(uscities, coords = c("lng", "lat"), crs = 4326) %>%
  filter(!state_name %in% c("Puerto Rico", "Alaska", "Hawaii"))

eqdc_uscities = st_transform(sf_uscities, eqdc)
```

# Question 2

#2.1 - Distance to USA Border (coastline or national) (km)
```{r,message=FALSE, warning=FALSE}
usmap_union = st_union(mapdata) %>%
  st_cast("MULTILINESTRING")

eqdc_uscities = eqdc_uscities %>% 
  mutate(distance_border = st_distance(eqdc_uscities, usmap_union),
         distance_border = units::set_units(distance_border, "km"),
         distance_border = units::drop_units(distance_border))

eqdc_uscities %>% 
  slice_max(distance_border, n = 5) %>%
  select(city, state_name, distance_border) %>% 
  as.data.frame(dist_usaborder_table) %>% 
  select(city, state_name, distance_border)
knitr::kable(dist_usaborder_df, caption = "Cities Furthest from USA Border",
               col.names = c("city","state", "distance"))
```
