---
title: "Geography 176A"
author: "[Stone Shi](https://mycraysh.github.io/StoneGIS/)"
subtitle: 'Lab 04: Tesselations, Point-in-Polygon'
output:
  html_document:
    theme: journal
---
```{r library,include=FALSE, echo=FALSE}
library(tidyverse)
library(knitr)
library(USAboundaries)
library(sf)
library(units)
library(rmapshaper)
library(readxl)
library(ggplot2)
library(leaflet)
library(leafpop)
library(plotrix)
library(gghighlight)
```

# Question 1

## 1.1
```{r,message=FALSE, warning=FALSE}
mapdata = USAboundaries::us_counties() %>%
  filter(!state_name %in% c("Puerto Rico", "Alaska", "Hawaii")) %>%
  st_transform(5070)
mapnpts = mapview::npts(mapdata)
mapdel = ms_simplify(mapdata, keep = 0.05)
delnpts = mapview::npts(mapdel)

```

## 1.2
```{r,message=FALSE, warning=FALSE}
counties_cent = st_centroid(mapdata) %>% 
  st_combine() %>%
  st_cast("MULTIPOINT")
```

## 1.3
```{r,message=FALSE, warning=FALSE, echo=FALSE}
countiesun = st_union(counties_cent)

ct_voroni = st_voronoi(counties_cent) %>%
  st_cast() %>%
  st_as_sf %>%
  mutate(id=1:n())

ct_trian = st_triangulate(counties_cent) %>%
  st_cast() %>%
  st_as_sf() %>%
  mutate(id=1:n())

ct_grid_cv =st_make_grid(mapdata, n = c(70, 50)) %>%
  st_cast() %>%
  st_as_sf() %>%
  mutate(id = 1:n())

ct_hexagon_cv =  st_make_grid(mapdata, n = c(70, 50), square = FALSE) %>%
  st_cast() %>%
  st_as_sf() %>%
  mutate(id = 1:n())

```


## 1.4 - 1.5
```{r,message=FALSE, warning=FALSE}
ct_voroni= st_intersection(ct_voroni, st_union(mapdel))
ct_trian = st_intersection(ct_trian, st_union(mapdel))
ct_grid_cv = st_intersection(ct_grid_cv, st_union(mapdel))
ct_hexagon_cv = st_intersection(ct_hexagon_cv, st_union(mapdel))
```

## 1.6
```{r,message=FALSE, warning=FALSE, echo=FALSE}
plot_tess = function(data, title)
  {
  ggplot() + 
    geom_sf(data = data, fill = "white", col = "navy", size = .2)+
    theme_void()+
    labs(title = title, caption = paste("This tesselation has:", nrow(data), "tiles" )) +
    theme(plot.title = element_text(hjust = .5, color =  "navy"))
}

plot_tess(data = mapdel, "Original Data of the Counties")

plot_tess(data =ct_voroni, "Voroni Data of the Counties") +
   geom_sf(data = counties_cent, col = "darkred", size = .2)

plot_tess(data =ct_trian, "Trianangle Data of the Counties") +
   geom_sf(data = counties_cent, col = "darkred", size = .2)


plot_tess(data =ct_grid_cv, "Square Coverage of the Counties")


plot_tess(data =ct_hexagon_cv, "Hexagonal Coverage of the Counties")
```
# Question 2
## 2.1-2.2
```{r,message=FALSE, warning=FALSE}
tessellation = function(data, title) 
  {area = st_area(data) %>% 
    units::set_units("km2") %>%
    units::drop_units() 
  data_frame(title, nrow(data), mean(area), sd(area), sum(area)) }
```

## 2.3
```{r,message=FALSE, warning=FALSE}
tess_summary = bind_rows(
   tessellation(mapdel, "Counties"),
   tessellation(ct_voroni, "Voroni"),
   tessellation(ct_trian, "Triangulation"),
   tessellation(ct_grid_cv, "Grid"),
   tessellation(ct_hexagon_cv, "Hexagon"))
```

## 2.4
```{r,message=FALSE, warning=FALSE,echo=FALSE}
knitr::kable(tess_summary,
caption = "Tessellation Characteristics",
col.names = c("Type","Numbers","Mean Area/km^2","Std Deviation Area/km^2","Covered Area/km^2"),
format.args = list(big.mark = ","))
```

## 2.5
```{r,message=FALSE, warning=FALSE}

#Different tessellation methods may obtain different data during calculation.
#County tessellation is the most standard method, which provides accurate information for the programmer.
#The Voroni tessellation is more detailed and varied when slicing the areas surrounding the center of the map.Based on its calculation method, the Voroni tessellation can effectively analyze the regional density.The area that Voroni tessellation covers is equal to the original area.
#The Triangle tessellation divide the map data into several triangles.The standard deviation of the triangle tessellation is smaller than the original and Voroni tessellation.
#Its average area is half that of the original tessellation. Therefore, the area covered by the triangle tessellation is slightly smaller than the original area.
#Both Grid and Hexagon tessellations divide surfaces into areas of equal area, which increase accuracy in calculating data relative to "per capita". The average area and total coverage area of these two tessellations are both larger than the original.
#In the region of quadrilateral subdivision, only the x and y coordinates need to be specified, which means it can be used widely.
#In these four tessellations, the hexagon tessellation can cover the most accurate surface area.
```

# Question 3

## 3.1
```{r,message=FALSE, warning=FALSE}
NID = read_excel('D:/LifeInUCSB/Study/GEOG176A/week2/assignment5/geog-176A-labs/data/NID2019.xlsx') %>% 
  filter(!is.na(LONGITUDE)) %>% 
  filter(!is.na(LATITUDE))

stDAM <- NID %>%
  st_as_sf(coords = c("LONGITUDE", "LATITUDE"), crs = 4326) %>%
  st_transform(5070) 
```

## 3.2
```{r,message=FALSE, warning=FALSE}
point_in_polygon = function(points, polygon, id)
  {st_join(polygon, points) %>%
    st_drop_geometry() %>%
    dplyr::count(.data[[id]]) %>%
    setNames(c(id, "n")) %>%
    left_join(polygon, by = id) %>%
    st_as_sf()
    }
```

## 3.3
```{r,message=FALSE, warning=FALSE}
oripol = point_in_polygon(stDAM, mapdel,"geoid")
vorpol = point_in_polygon(stDAM, ct_voroni,"id")
trianpol = point_in_polygon(stDAM,ct_trian,"id")
gridpol = point_in_polygon(stDAM,ct_grid_cv,"id")
hexpol = point_in_polygon(stDAM,ct_hexagon_cv,"id")
```
## 3.4
```{r,message=FALSE, warning=FALSE,echo=FALSE,echo=FALSE}
plot_in_polygon2 = function(data, title)
  {ggplot() +
    geom_sf(data = data, aes(fill = log(n)), alpha = 1, size = .2, col = NA) +
    scale_fill_viridis_c()+
    theme_dark()+
    theme(legend.position = 'none',
          plot.title = element_text(face = "bold", color = "black", size = 20,hjust = .5)) +
    labs(title = title,
         caption = paste0(sum(data$n), "Number of Dams"))}
```

## 3.5
```{r,message=FALSE, warning=FALSE,echo=FALSE}
plot_in_polygon2(oripol, "Number of Dams In Countries")
plot_in_polygon2(vorpol, "Number of Dams by Voroni Pattern")
plot_in_polygon2(trianpol, "Number of Dams by Triangle Pattern")
plot_in_polygon2(gridpol, "Number of Dams by Grid Pattern")
plot_in_polygon2(hexpol, "Number of Dams by Hexagon Pattern")
```


## 3.6
```{r,message=FALSE, warning=FALSE}
#The influence of the hexagon tessellated surface in the visualization of point counts is obivious. 
#The visualized data after the Voroni tessellation restores the original data most clearly, because its mean area and standard deviation have no difference with the original data.
#The visual data of triangle tessellation is similar to Voroni tessellation, but the scale range of each region is smaller. This type of tessellation presents a more uniform data distribution than the Voroni. However, it has more fragmented regions.
#Grids and hexagonal tessellations have the same mean area, which the standard deviation among these areas can be ignored. However, this tessellation delineates a pattern that lacks the detail of the original image. Both tessellations cover an area larger than the original total area of about 600,000 square kilometers.
#Because MAUP is a source of statistical bias that can significantly impact the results of statistical hypothesis tests, the grid tessellations based on point measures cannot be chosen. As a result,I choose to use Voroni tessellation to reduce the bias of MAUP. Also, Voroni could cover the accurate area of the dams data.
```

# Question 4

## 4.1-4.2
```{r,message=FALSE, warning=FALSE, echo=FALSE}
#The usage split
nid_classifier = data.frame(abbr = c("I","N","S","R"),
                 purpose = c("Irrigation","Navigation","Water Supply","Recreation"))
dam_freq <- strsplit(stDAM$PURPOSES, split = "") %>%
  unlist() %>% 
  table() %>% 
  as.data.frame() %>% 
  setNames(c("abbr", "count")) %>% 
  left_join(nid_classifier) %>% 
  mutate(lab = paste0(purpose, "\n(", abbr, ")"))

#Irrigation(I)
irrigation <- stDAM %>% 
  filter(grepl("I", stDAM$PURPOSES)==TRUE)
irripol = point_in_polygon(irrigation,ct_voroni,"id")
plot_in_polygon2(irripol, "Areas which dams are likely used for irrigation") +
  gghighlight::gghighlight(n > mean(n) + 1) 

#Navigation
navigation <- stDAM %>% 
  filter(grepl("N", stDAM$PURPOSES)==TRUE)
navipol = point_in_polygon(navigation,ct_voroni,"id")
plot_in_polygon2(navipol, "Areas which dams are likely used for navigation") +
  gghighlight::gghighlight(n > mean(n) + 1) 

#Water Supply
water <- stDAM %>% 
  filter(grepl("S", stDAM$PURPOSES)==TRUE)
watpol = point_in_polygon(water,ct_voroni,"id")
plot_in_polygon2(watpol,"Areas which dams are likely used for water supply") +
  gghighlight::gghighlight(n > mean(n) + 1) 
#Recreation
recreation <- stDAM %>% 
  filter(grepl("R", stDAM$PURPOSES)==TRUE)
recpol = point_in_polygon(recreation,ct_voroni,"id")
plot_in_polygon2(recpol, "Areas which dams are likely used for recreation") +
  gghighlight::gghighlight(n > mean(n) + 1) 
```

## 4.3
```{r, warning = FALSE, message = FALSE}
#The geographical distribution of dams used in different fields has its significance.The results of the dam's geographical distribution are consistent with their use.
#Dams used for irrigation are widely distributed across the Western Plateau, the Eastern Appalachian Mountains, and the lower Mississippi River.These areas are well cultivated which need irrigation.
#Dams used for navigation are relatively less than others,mostly located in the northeast and are used to regulate elevation differences in water levels so that ships can navigate. Ships with cargo in the Great Lakes region are very frequent.
#Dams used for water supply are mainly distributed in populated areas of California and north east, as well as the lower Mississippi River. Water supply should be guaranteed because of their high population density in these regions.
#Dams used for recreation are mainly located in the eastern United States, probably because they are more accessible to residents. In the Midwest, due to the terrain and climate, it is difficult for dams to be developed as recreation facilities and visited by tourists.
```

# Extra credit
```{r message=FALSE, warning=FALSE, echo=FALSE}
missi = read_sf('D:/LifeInUCSB/Study/GEOG176A/week2/assignment5/geog-176A-labs/data/MajorRivers/MajorRivers.shp')
missi = missi %>% 
  filter(SYSTEM == "Mississippi")

stDAMbig = stDAM %>%
  filter(HAZARD == "H", grepl("C", PURPOSES)) %>%
  group_by(STATE) %>%
  slice_max(NID_STORAGE) %>%
  select("DAM_NAME", "NID_STORAGE", "PURPOSES", "YEAR_COMPLETED")

big_dam = st_transform(stDAMbig, 4326)
pop_dam = leafpop::popupTable(st_drop_geometry(stDAMbig), feature.id = FALSE, row.numbers = FALSE)
leaflet() %>% 
  addProviderTiles(providers$CartoDB) %>% 
  addPolylines(data = missi) %>%
  addCircleMarkers(data = big_dam,radius = ~NID_STORAGE / 1500000, color = "red",stroke = FALSE,fillOpacity = 1, popup = ~pop_dam)
```
